import MeasurementInducedDimensions

#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T01_length_and_time_labels_are_distinct
#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T02_relabel_preserves_operational_map
#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T03_same_operational_map_allows_distinct_dimensions
#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T04_dimension_relabel_preserves_premetric_ontology
#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T05_dimension_not_determined_by_premetric_ontology
#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T06_speed_numeral_reencoding_preserves_causal_boundary
#print axioms QIKVRT.V2.Physics.MeasurementInducedDimensions.MID_T07_same_boundary_allows_c_299792458_or_1
