// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Copyright 2026 Ingolf Lohmann.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../docs/mesh-observatory/index.html'),'utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const H='a'.repeat(40), T='b'.repeat(40), B='c'.repeat(40), NEXT='d'.repeat(40);
function harness(){
  const elements=new Map(),timers=new Map(),requests=[],sources=[];
  let timerID=0,now=0,fail=null,hold=false,waiting=[],head=H,drift=false,mainReads=0;
  function element(id){if(!elements.has(id)){const classes=new Set();elements.set(id,{textContent:'',innerHTML:'',children:[],classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},listeners:{},addEventListener(k,f){this.listeners[k]=f},prepend(x){this.children.unshift(x)},get lastChild(){return {remove:()=>this.children.pop()}}})}return elements.get(id)}
  class ES {constructor(url){this.url=url;this.listeners={};this.closed=false;sources.push(this)}addEventListener(k,f){this.listeners[k]=f}close(){this.closed=true}emit(k,data,lastEventId=''){this.listeners[k]?.({data:typeof data==='string'?data:JSON.stringify(data),lastEventId})}open(){this.onopen()}ready(id=null){this.emit('qikvrt-ready',{schema:'qikvrt_stream_boundary_v1',last_event_id:id})}}
  function response(url){const suffix=url.split('Goldkelch/qik-vrt')[1];if(fail)return {ok:false,status:fail};let data;if(suffix==='/branches/main'){mainReads++;data={commit:{sha:drift&&mainReads%2===0?NEXT:head}}}else if(suffix.startsWith('/pulls/')){const n=Number(suffix.split('/').at(-1));data={number:n,title:'<title>',state:'open',draft:true,mergeable:null,head:{sha:head,repo:{full_name:'Goldkelch/qik-vrt'}},base:{sha:B},requested_reviewers:[{login:'Goldkelch'}]}}else{data={sha:suffix.split('/').at(-1),tree:{sha:T}}}return {ok:true,json:async()=>data}}
  const context={console,Map,Set,Date,JSON,Error,Number,String,Promise,AbortController,performance:{now:()=>now},location:{protocol:'https:'},EventSource:ES,queueMicrotask,setTimeout(fn,ms){const id=++timerID;timers.set(id,{fn,ms});return id},clearTimeout:id=>timers.delete(id),document:{getElementById:element,createElement:()=>element(Symbol()),addEventListener(){}},window:{addEventListener(){}},fetch(url,options){requests.push({url,options});if(!hold)return Promise.resolve(response(url));return new Promise((resolve,reject)=>{const abort=()=>reject(new Error('AbortError'));options.signal.addEventListener('abort',abort,{once:true});waiting.push(()=>{options.signal.removeEventListener('abort',abort);resolve(response(url))});});}};
  vm.createContext(context);vm.runInContext(code,context);
  return {elements,requests,sources,timers,element,get source(){return sources.at(-1)},get head(){return head},set head(x){head=x},set fail(x){fail=x},set hold(x){hold=x},set drift(x){drift=x},release(){hold=false;const list=waiting;waiting=[];list.forEach(f=>f())},fire(ms){now+=ms;const list=[...timers];for(const [id,t] of list)if(t.ms===ms){timers.delete(id);t.fn()}},click(){element('refresh').listeners.click()},allEvents(){return element('events').children.map(c=>c.innerHTML).join('\n')}};
}
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve))};
function receipt(id='e1',overrides={}){return {schema:'qikvrt_live_event_v1',event_id:id,observed_at:'2026-09-15T13:00:00Z',repository:'Goldkelch/qik-vrt',subject:{kind:'pull_request',pull_request:1071,head_sha:H,base_sha:B},phase:'P2',verb:'READBACK',causal_state:'HOLD',source:{type:'workflow_run',id:'1'},productive_effect:false,effect_ack:'PENDING',payload:{},...overrides}}
async function start(h){h.source.open();h.source.ready();await flush()}
test('source is event driven; opening/idle/keepalive is not readback',async()=>{const h=harness();assert.equal(h.source.url,'/events');assert.equal(h.requests.length,0);h.source.open();await flush();assert.equal(h.requests.length,0);h.source.ready();await flush();assert.equal(h.requests.length,12);h.source.ready();await flush();assert.equal(h.requests.length,12);assert.ok(h.requests.every(r=>r.options.cache==='no-store'&&r.options.credentials==='omit'));assert.doesNotMatch(code,/setInterval|setTimeout\s*\(\s*(refresh|drain|connect|enqueue)/)});
test('freshness expiry only invalidates and never fetches',async()=>{const h=harness();await start(h);h.fire(60000);await flush();assert.equal(h.requests.length,12);assert.match(h.element('readback').textContent,/STALE.*READBACK_EXPIRED/);assert.ok(h.element('lanes').classList.contains('stale'))});
test('native burst coalesces; duplicate/unrelated receipts do not refresh',async()=>{const h=harness();await start(h);for(let i=1;i<=20;i++)h.source.emit('qikvrt',receipt('e'+i),'e'+i);h.source.ready('e20');await flush();assert.equal(h.requests.length,24);h.source.emit('qikvrt',receipt('e20'),'e20');h.source.ready('e20');await flush();assert.equal(h.requests.length,24);h.source.emit('qikvrt',receipt('other',{repository:'ingolf-lohmann/qik-vrt'}),'other');h.source.ready('other');await flush();assert.equal(h.requests.length,24)});
test('event head and DONE claims are not snapshot or effect evidence',async()=>{const h=harness();await start(h);h.source.emit('qikvrt',receipt('untrusted',{subject:{kind:'trusted_main',head_sha:NEXT},productive_effect:true,effect_ack:'DONE'}),'untrusted');h.source.ready('untrusted');await flush();assert.match(h.element('mainsha').textContent,new RegExp(H));assert.doesNotMatch(h.element('mainsha').textContent,new RegExp(NEXT));assert.match(html,/EFFECT_ACK_DONE = OPEN/);assert.doesNotMatch(code,/effect_ack\s*===?\s*['"]DONE/)});
test('mutation reports reset; trees and unknown mergeability remain explicit',async()=>{const h=harness();await start(h);h.head=NEXT;h.source.emit('qikvrt',receipt(),'e1');h.source.ready('e1');await flush();assert.match(h.allEvents(),/P2\+ RESET/);assert.match(h.element('mainsha').textContent,new RegExp(NEXT+'.*'+T));assert.match(h.element('lanes').innerHTML,/unknown/)});
test('readback failure retains history as stale, without retry',async()=>{const h=harness();await start(h);const old=h.element('mainsha').textContent,last=h.element('last').textContent;h.fail=429;h.click();await flush();assert.equal(h.element('mainsha').textContent,old);assert.equal(h.element('last').textContent,last);assert.match(h.element('readback').textContent,/HOLD.*429/);const n=h.requests.length;h.fire(60000);await flush();assert.equal(h.requests.length,n)});
test('head drift during readback cannot be published',async()=>{const h=harness();h.drift=true;await start(h);assert.match(h.element('readback').textContent,/HEAD_OR_BASE_DRIFT/);assert.equal(h.element('mainsha').textContent,'')});
test('disconnect fences in-flight success; reopen alone does not fetch',async()=>{const h=harness();h.hold=true;h.source.open();h.source.ready();await flush();h.source.onerror();h.release();await flush();assert.equal(h.element('mainsha').textContent,'');assert.match(h.element('readback').textContent,/STREAM_DISCONNECTED/);const count=h.requests.length;h.source.open();await flush();assert.equal(h.requests.length,count);h.source.ready();await flush();assert.match(h.element('readback').textContent,/READBACK_BOUND/)});
test('new event during readback fences the old generation',async()=>{const h=harness();await start(h);h.hold=true;h.click();await flush();h.head=NEXT;h.source.emit('qikvrt',receipt(),'e1');h.source.ready('e1');h.release();await flush();assert.match(h.element('mainsha').textContent,new RegExp(NEXT));assert.match(h.allEvents(),/P2\+ RESET/)});
test('request deadline fails closed without scheduled recovery',async()=>{const h=harness();h.hold=true;h.source.open();h.source.ready();await flush();h.fire(15000);await flush();assert.match(h.element('readback').textContent,/HOLD.*AbortError/);assert.equal(h.requests.length,4)});
test('malformed, mismatched, conflicting and gap frames close the stream',async()=>{for(const kind of ['malformed','mismatch','conflict','gap']){const h=harness();await start(h);const n=h.requests.length;if(kind==='malformed')h.source.emit('qikvrt','{');if(kind==='mismatch')h.source.emit('qikvrt',receipt(),'wrong');if(kind==='conflict'){h.source.emit('qikvrt',receipt(),'e1');h.source.emit('qikvrt',receipt('e1',{verb:'HOLD'}),'e1')}if(kind==='gap')h.source.emit('qikvrt-gap',{reason:'CURSOR_NOT_FOUND'});await flush();assert.equal(h.source.closed,true,kind);assert.match(h.element('readback').textContent,/HOLD/);assert.equal(h.requests.length,n,kind)}});
test('existing repository-kind producer receipts wake the same consumer',async()=>{const h=harness();await start(h);h.source.emit('qikvrt',receipt('producer',{subject:{kind:'repository',head_sha:H},source:{type:'pull_request',id:'run'}}),'producer');h.source.ready('producer');await flush();assert.equal(h.requests.length,24)});
test('closed/replaced transport callbacks cannot revive freshness',async()=>{const h=harness();await start(h);const old=h.source;old.emit('qikvrt-gap',{});const n=h.requests.length;old.ready();await flush();assert.equal(h.requests.length,n);h.click();assert.notEqual(h.source,old);old.onerror();old.open();old.ready();await flush();assert.equal(h.requests.length,n);await start(h);assert.match(h.element('readback').textContent,/READBACK_BOUND/)});
test('missing required envelope members fail closed',async()=>{const h=harness();await start(h);const e=receipt();delete e.effect_ack;h.source.emit('qikvrt',e,'e1');h.source.ready('e1');await flush();assert.equal(h.source.closed,true);assert.equal(h.requests.length,12);assert.match(h.element('readback').textContent,/INVALID_EVENT_ENVELOPE/)});
