# Copyright (c) 2026 Ingolf Lohmann. Repository licensing applies.
source 'https://rubygems.org'
ruby '~> 3.3.0'
# API-only Rails: no database, mail, jobs, storage or asset compiler required.
gem 'railties', '= 8.1.3.1'

group :test do
  gem 'minitest', '= 5.20.0'
  gem 'webrick', '= 1.9.1'
end
