import QIKVRTFormalization.TEMDD.ConservativeUniversality

/-!
# Constructive U3 witness for refinement-generated source languages

This module proves a non-vacuous first U3 theorem for an explicit infinite class
of source languages generated by restricting a target TEMDD semantic surface to
admissible state and subject subtypes.  Membership in the class is structural;
it does not assume the existence of an embedding.
-/

namespace QIKVRT.V2.TEMDD.ConservativeUniversality

/--
A source language obtained by restricting the target state and subject spaces.
Requirements, evidence, actions and authority remain unchanged; all semantic
relations are inherited from the target through subtype projection.
-/
def refinementSource
    (T : TargetLanguage)
    (stateAllowed : T.State → Prop)
    (subjectAllowed : T.Subject → Prop) : SourceLanguage where
  State := { s : T.State // stateAllowed s }
  Subject := { σ : T.Subject // subjectAllowed σ }
  Requirement := T.Requirement
  Evidence := T.Evidence
  Action := T.Action
  Authority := T.Authority
  Satisfies := fun s r => T.Satisfies s.1 r
  Bound := fun e σ => T.Bound e σ.1
  Step := fun s a s' => T.Step s.1 a s'.1
  Done := fun r e σ s => T.Done r e σ.1 s.1
  ClaimStrength := T.ClaimStrength
  Authorized := T.Authorized

/--
Canonical conservative inclusion of every refinement-generated source language
into the target, assuming every one-step target transition is reachable.
-/
def refinementEmbedding
    (T : TargetLanguage)
    (hStepReachable : ∀ s a s', T.Step s a s' → T.Reachable s a s')
    (stateAllowed : T.State → Prop)
    (subjectAllowed : T.Subject → Prop) :
    ConservativeEmbedding (refinementSource T stateAllowed subjectAllowed) T where
  mapState := fun s => s.1
  mapSubject := fun σ => σ.1
  mapRequirement := id
  mapEvidence := id
  mapAction := id
  mapAuthority := id
  requirement_preserved := by
    intro s r
    rfl
  binding_preserved := by
    intro e σ
    rfl
  injective_subject := by
    intro σ σ' h
    apply Subtype.ext
    exact h
  evidence_non_amplifying := by
    intro e
    exact Nat.le_refl _
  transition_preserved := by
    intro s a s' h
    exact hStepReachable s.1 a s'.1 h
  authority_preserved := by
    intro authority action h
    exact h
  completion_reflected := by
    intro r e σ s h
    exact h

/--
Structural admissible class generated by state/subject refinements of `T`.
Crucially, the definition does not quantify over or assume a
`ConservativeEmbedding` witness.
-/
def RefinementAdmissibleClass (T : TargetLanguage) : AdmissibleClass :=
  fun L => ∃ (stateAllowed : T.State → Prop) (subjectAllowed : T.Subject → Prop),
    L = refinementSource T stateAllowed subjectAllowed

/--
First proved U3 instance: every source language in the independently structural
refinement-generated class admits a conservative semantic embedding into `T`.
-/
theorem temdd_u3_for_refinement_class
    (T : TargetLanguage)
    (hStepReachable : ∀ s a s', T.Step s a s' → T.Reachable s a s') :
    U3ConservativeSemanticUniversality (RefinementAdmissibleClass T) T := by
  intro L hL
  rcases hL with ⟨stateAllowed, subjectAllowed, rfl⟩
  exact ⟨refinementEmbedding T hStepReachable stateAllowed subjectAllowed⟩

/-- The refinement class is nonempty: the unrestricted target image belongs. -/
theorem refinement_class_nonempty (T : TargetLanguage) :
    ∃ L : SourceLanguage, RefinementAdmissibleClass T L := by
  refine ⟨refinementSource T (fun _ => True) (fun _ => True), ?_⟩
  exact ⟨fun _ => True, fun _ => True, rfl⟩

/--
Concrete no-truth-manufacture corollary for every refinement-generated source:
target completion reflects directly to source completion.
-/
theorem refinement_completion_reflection
    (T : TargetLanguage)
    (hStepReachable : ∀ s a s', T.Step s a s' → T.Reachable s a s')
    (stateAllowed : T.State → Prop)
    (subjectAllowed : T.Subject → Prop)
    (r : T.Requirement)
    (e : T.Evidence)
    (σ : { σ : T.Subject // subjectAllowed σ })
    (s : { s : T.State // stateAllowed s })
    (hDone : T.Done r e σ.1 s.1) :
    (refinementSource T stateAllowed subjectAllowed).Done r e σ s := by
  exact (refinementEmbedding T hStepReachable stateAllowed subjectAllowed).completion_reflected
    r e σ s hDone

end QIKVRT.V2.TEMDD.ConservativeUniversality
